name: Paveral
version: '${project.version}'
main: me.powerspieler.paveral.Paveral
api-version: '1.21'

commands:
  guide:
    description: Used for the guide book to open up sub-pages
  test:
    description: Execute Test Code
    permission: paveral.dev
  cooldown:
    description: Soosmose
    permission: paveral.dev
  items:
    description: Request a paveral item
    permission: paveral.dev

permissions:
  paveral.dev:
    description: Allows Paveral Development Commands
    default: op
