name: Paveral
version: 0.0.1
main: me.powerspieler.paveral.Paveral
api-version: 1.19

commands:
  test:
    description: Execute Test Code
  cooldown:
    description: Soosmose
  items:
    description: Request a paveral item
